In [2]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])

In [4]:
print(a.ndim)

1


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.size)

4


In [8]:
print(len(a))

4


In [9]:
print(a.dtype)

int32


In [10]:
a = np.array([0,1,2,3.14])

In [11]:
print(a.dtype)

float64


In [12]:
a

array([0.  , 1.  , 2.  , 3.14])

In [13]:
b = np.array([0, 'Hello'])

In [14]:
print(b.dtype)

<U11


In [15]:
b

array(['0', 'Hello'], dtype='<U11')

In [16]:
c = np.array([[1,2],[3,4]])

In [17]:
c

array([[1, 2],
       [3, 4]])

In [18]:
print(c.ndim)

2


In [19]:
print(c.size)

4


In [20]:
print(c.shape)

(2, 2)


In [21]:
print(len(c))

2


In [22]:
d = np.array([[[0 , 1, 2, 3] ,[4 , 5, 6, 7]] ,[[8 , 9, 10,
11] ,[12 , 13, 14, 15]]])

In [23]:
print(d.shape)

(2, 2, 4)


In [24]:
d.size

16

In [25]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [30]:
d[0,1,0]

4

In [31]:
d[1,0,2]

10

In [26]:
b

array(['0', 'Hello'], dtype='<U11')

In [27]:
c

array([[1, 2],
       [3, 4]])

In [28]:
c[1,0]

3

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
np.full((3,2),np.inf)

array([[inf, inf],
       [inf, inf],
       [inf, inf]])

In [43]:
np.pi

3.141592653589793

In [44]:
np.e

2.718281828459045

In [45]:
A = np.array([[10,20],[30,40]])

In [46]:
A

array([[10, 20],
       [30, 40]])

In [47]:
B = np.array([[1,1],[1,1]])

In [48]:
B

array([[1, 1],
       [1, 1]])

In [49]:
A+B

array([[11, 21],
       [31, 41]])

In [50]:
A-B

array([[ 9, 19],
       [29, 39]])

In [51]:
A*B

array([[10, 20],
       [30, 40]])

In [52]:
A/B

array([[10., 20.],
       [30., 40.]])

In [53]:
A@B

array([[30, 30],
       [70, 70]])

In [54]:
A.dot(B)

array([[30, 30],
       [70, 70]])

In [55]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [56]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [57]:
n = 135

In [58]:
1**1 + 3**2 + 5**3

135

In [69]:
sum((int(j)**(i+1) for i,j in enumerate(str(135))))

135

In [60]:
enumerate(str(135))

In [61]:
print(enumerate(str(135)))

In [64]:
for i,j in enumerate(str(135)):
    print(i,j)

0 1
1 3
2 5


In [70]:
A

array([[10, 20],
       [30, 40]])

In [71]:
A[1]

array([30, 40])

In [72]:
a = np. array (
[[0 ,1 ,2 ,3 ,4 ,5] ,
[10 ,11 ,12 ,13 ,14 ,15] ,
[20 ,21 ,22 ,23 ,24 ,25] ,
[30 ,31 ,32 ,33 ,34 ,35] ,
[40 ,41 ,42 ,43 ,44 ,45] ,
[50 ,51 ,52 ,53 ,54 ,55]])

In [74]:
a[0,(3,4)]

array([3, 4])

In [75]:
A

array([[10, 20],
       [30, 40]])

In [76]:
AA = A

In [77]:
AA

array([[10, 20],
       [30, 40]])

In [78]:
AA[1,1] = 100

In [79]:
AA

array([[ 10,  20],
       [ 30, 100]])

In [80]:
A

array([[ 10,  20],
       [ 30, 100]])