In [1]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0]) 

In [2]:
print(a+b)

[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [3]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)

print('Modified array is:')
for x in np.nditer(a):
   print(x,end=' ')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is:
0 5 10 15 20 25 30 35 40 45 50 55 

In [4]:
b = a.T

In [5]:
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [6]:
d = b.copy(order='F')

In [7]:
d

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [8]:
c = b.copy(order='C')

In [9]:
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [11]:
for x in np.nditer(b):
    print(x,end=' ')

0 5 10 15 20 25 30 35 40 45 50 55 

In [12]:
for x in np.nditer(c):
    print(x,end=' ')

0 20 40 5 25 45 10 30 50 15 35 55 

In [13]:
for x in np.nditer(d):
    print(x,end=' ')

0 5 10 15 20 25 30 35 40 45 50 55 

In [14]:
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [16]:
eyeM = np.zeros_like(b)

In [17]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] #creates a newaxis and makes the array into two-dimentionsl


array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [18]:
a.shape

(4,)

In [21]:
a[np.newaxis,:].shape

(1, 4)

In [24]:
a[np.newaxis,:]

array([[ 0., 10., 20., 30.]])

In [25]:
a[0]

0.0

In [26]:
a[2]

20.0

In [27]:
a = [[1,2],[3,4]]

In [28]:
b = [[5,6],[7,8]]

In [31]:
np.hstack([a,b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
a

[[1, 2], [3, 4]]

In [36]:
np.append(a,[[5,5],[6,6]],axis=1)

array([[1, 2, 5, 5],
       [3, 4, 6, 6]])

In [37]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) 

In [39]:
np.delete(a,np.s_[::2])

array([ 2,  4,  6,  8, 10])

In [42]:
a = np.linspace(1,10,10,dtype='int')

In [43]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.delete(a,np.s_[::2])

array([ 2,  4,  6,  8, 10])

In [48]:
np.random.uniform(1,10,size=(5,5))

array([[3.65337442, 7.96997439, 4.88995792, 4.97727748, 2.51149171],
       [2.14784804, 7.06136704, 5.66609158, 6.1462506 , 3.72699451],
       [8.39470523, 1.40926692, 7.88986391, 5.75305184, 4.17033431],
       [6.758617  , 1.490124  , 8.89054433, 2.36073117, 3.95434031],
       [8.34702816, 3.63863712, 3.94323504, 6.87350405, 8.96852996]])