In [1]:
import math as m
import random as r

In [12]:
R = [[r.random() for i in range(0,3)] for j in range(0,3)]

In [16]:
R

[[0.6364247298247782, 0.7038621433518317, 0.10052125620229646],
 [0.2926953730655778, 0.08627917460132617, 0.5341905091442556],
 [0.13607583800716705, 0.5028830270600307, 0.43101587629364446]]

In [10]:
list(map(m.sin,[30,60,90]))

[-0.9880316240928618, -0.3048106211022167, 0.8939966636005579]

In [11]:
[m.sin(x) for x in [30,60,90]]

[-0.9880316240928618, -0.3048106211022167, 0.8939966636005579]

In [17]:
import numpy as np

In [45]:
A = np.array([[[10.0,20,30],[2,4,5]],[[11,21,31],[3,7,9]]])

In [46]:
print(A)

[[[10. 20. 30.]
  [ 2.  4.  5.]]

 [[11. 21. 31.]
  [ 3.  7.  9.]]]


In [42]:
type(A)

numpy.ndarray

In [47]:
A.ndim

3

In [48]:
A.shape

(2, 2, 3)

In [36]:
A.dtype

dtype('float64')

In [59]:
A[0,0,0:4]

array([10., 20., 30.])

In [38]:
np.sin(A)

array([[-0.54402111,  0.91294525, -0.98803162],
       [ 0.90929743, -0.7568025 , -0.95892427]])

In [39]:
len(A)

2

In [61]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [63]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [71]:
np.eye(6,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [76]:
np.full([5,3],21.6)

array([[21.6, 21.6, 21.6],
       [21.6, 21.6, 21.6],
       [21.6, 21.6, 21.6],
       [21.6, 21.6, 21.6],
       [21.6, 21.6, 21.6]])

In [80]:
np.empty([4,3])

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
A

array([[[10., 20., 30.],
        [ 2.,  4.,  5.]],

       [[11., 21., 31.],
        [ 3.,  7.,  9.]]])

In [82]:
A = np.array([[1,2,3],[4,5,6]])

In [83]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
A.shape

(2, 3)

In [87]:
B = A.reshape(3,2)

In [86]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
B = B.reshape(6,1)

In [92]:
B

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [93]:
A = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [94]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
A = np.arange(1,13).reshape(3,4)

In [98]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
A.flatten('F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])