In [17]:
no = 23.235

In [18]:
decipart = int(str(no).split(".")[1])

In [24]:
def intEvenOdd(num):
    if num%2 == 0:
        return "Even Number"
    else:
        return "Odd Number"

def floatEvenOdd(num):
    if int(str(num).split(".")[1]) == 0:
        return intEvenOdd(int(num))
    else:
        return intEvenOdd(int(str(num).split(".")[1]))

In [29]:
floatEvenOdd(122.0)

'Even Number'

In [30]:
import numpy as np

In [34]:
np.full(2,3)

array([3, 3])

In [35]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passe

In [39]:
A = np.full((2,2),10)

In [43]:
A.shape

(2, 2)

In [42]:
A.ndim

2

In [46]:
N = np.full((2,2),20)

In [47]:
A*N

array([[200, 200],
       [200, 200]])

In [49]:
A.dot(N)

array([[400, 400],
       [400, 400]])

In [50]:
A@N

array([[400, 400],
       [400, 400]])

In [51]:
A*N

array([[200, 200],
       [200, 200]])

In [52]:
A

array([[10, 10],
       [10, 10]])

In [53]:
N

array([[20, 20],
       [20, 20]])

In [54]:
I = np.eye(2)

In [55]:
I

array([[1., 0.],
       [0., 1.]])

In [56]:
I*N

array([[20.,  0.],
       [ 0., 20.]])

In [57]:
I@N

array([[20., 20.],
       [20., 20.]])