In [4]:
import numpy as np
  
arr = [[0, 1, 2, 3, 4], [5, 0, 6, 0, 7]]
  
noe = np.count_nonzero(arr, axis = 0)
  
print (noe) 

[1 1 2 1 2]


In [5]:
R = np.random.rand(5,3)

In [6]:
R

array([[0.56130685, 0.04015327, 0.63323115],
       [0.9640448 , 0.7694077 , 0.76659548],
       [0.38559474, 0.14997487, 0.05066759],
       [0.79996594, 0.45831672, 0.07884329],
       [0.90926282, 0.62987724, 0.22390443]])

In [7]:
ind = np.where(R < 0.5)

In [8]:
ind

(array([0, 2, 2, 2, 3, 3, 4], dtype=int64),
 array([1, 0, 1, 2, 1, 2, 2], dtype=int64))

In [9]:
R[ind] = 0

In [10]:
R

array([[0.56130685, 0.        , 0.63323115],
       [0.9640448 , 0.7694077 , 0.76659548],
       [0.        , 0.        , 0.        ],
       [0.79996594, 0.        , 0.        ],
       [0.90926282, 0.62987724, 0.        ]])

In [12]:
np.flipud(R)

array([[0.90926282, 0.62987724, 0.        ],
       [0.79996594, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.9640448 , 0.7694077 , 0.76659548],
       [0.56130685, 0.        , 0.63323115]])

In [28]:
R1 = np.random.randint(1,50,(3,7))

In [22]:
R2 = np.asarray(R1,dtype='float64')

In [29]:
R1 = R1.astype('float')

In [30]:
R1

array([[34., 21., 22., 30., 47.,  1., 44.],
       [ 2., 10.,  3., 41., 39., 30., 32.],
       [38., 22., 36., 46.,  9., 46., 40.]])

In [24]:
R2[np.where(R2 < 15)] = np.nan

In [25]:
R2

array([[15., nan, 46., 30., nan, 19., 33.],
       [nan, 26., 49., 38., 35., 20., 45.],
       [18., nan, nan, 19., 25., 38., 19.]])

In [34]:
inds = np.where(np.isnan(R2))

In [35]:
a[inds] = np.take(col_mean, inds[1])

NameError: name 'col_mean' is not defined

In [36]:
2934  0.48615268  0.06196785         nan]
 [ 0.64940216  0.74414127         nan         nan]]
)
# Obtain mean of columns as you need, nanmean is convenient.
col_mean = np.nanmean(a, axis=0)
print(col_mean)
[ 0.86726219  0.7030395   0.44528687  0.66640474]

#Find indices that you need to replace
inds = np.where(np.isnan(a))

#Place column means in the indices. Align the arrays using take
a[inds] = np.take(col_mean, inds[1])

print(a)
[[ 0.93230948  0.7030395   0.47773439  0.76998063]
 [ 0.94460779  0.87882456  0.79615838  0.56282885]
 [ 0.94272934  0.48615268  0.06196785  0.66640474]
 [ 0.64940216  0.74414127  0.44528687  0.66640474]]

SyntaxError: invalid syntax (Temp/ipykernel_4152/3409065961.py, line 1)

In [38]:
a = np.array([[ 0.93230948, np.nan,  0.47773439,  0.76998063], 
              [ 0.94460779,  0.87882456,  0.79615838,  0.56282885], 
              [ 0.94272934,  0.48615268,  0.06196785, np.nan],
              [ 0.64940216,  0.74414127,         np.nan,    np.nan]]
)

In [41]:
col_mean = np.nanmean(a, axis=0)
print(col_mean)

#Find indices that you need to replace
inds = np.where(np.isnan(a))

#Place column means in the indices. Align the arrays using take
a[inds] = np.take(col_mean, inds[1])

print(a)

[0.86726219 0.7030395  0.44528687 0.66640474]
[[0.93230948 0.7030395  0.47773439 0.76998063]
 [0.94460779 0.87882456 0.79615838 0.56282885]
 [0.94272934 0.48615268 0.06196785 0.66640474]
 [0.64940216 0.74414127 0.44528687 0.66640474]]


In [51]:
import numpy as np
import scipy
scipy.integrate.quad(lambda x: np.exp(-x**2),0,2)

(0.8820813907624215, 9.793070696178202e-15)

In [53]:
A = np.arange(1,11).reshape(5,2)

In [54]:
A[2,]

array([5, 6])

In [55]:
A

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [56]:
A[,3]

SyntaxError: invalid syntax (Temp/ipykernel_4152/2683338347.py, line 1)