In [1]:
import numpy as np

In [13]:
boolarr = np.full(10,True,dtype='bool')

In [11]:
print(boolarr)

[ True  True  True  True  True  True  True  True  True  True]


In [12]:
boolarr.dtype

dtype('bool')

In [14]:
riarr = np.random.randint(1,10,size=(10,))

In [15]:
print(riarr)

[8 3 6 8 2 6 9 1 9 7]


In [16]:
riarr[riarr % 2 == 0]

array([8, 6, 8, 2, 6])

In [17]:
riarr[riarr %2 != 0] = -1

In [18]:
print(riarr)

[ 8 -1  6  8  2  6 -1 -1 -1 -1]


In [19]:
a = np.random.randint(1,100,(10,))

In [21]:
print(a)

[30 61 68 95 79 63 50 18 32 76]


In [23]:
np.where(a >= 60)

(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [25]:
b = np.where(a >= 60, 5, a)

In [26]:
print(b)

[30  5  5  5  5  5 50 18 32  5]


In [27]:
a = np.array([1,2,3,2,3,4,3,5,8,6])
b = np.array([7,2,3,10,4,4,9,5,6,6])

In [28]:
print(a)

[1 2 3 2 3 4 3 5 8 6]


In [29]:
print(b)

[ 7  2  3 10  4  4  9  5  6  6]


In [30]:
np.where(a == b)

(array([1, 2, 5, 7, 9], dtype=int64),)

In [34]:
np.where((a >= 2) & (a <= 5))

(array([1, 2, 3, 4, 5, 6, 7], dtype=int64),)

In [46]:
a = np.linspace(10,20,6).reshape(3,2)

In [38]:
b = np.linspace(30,40,6).reshape(3,2)

In [41]:
print(a)

[[10. 12.]
 [14. 16.]
 [18. 20.]]


In [42]:
print(b)

[[30. 32.]
 [34. 36.]
 [38. 40.]]


In [40]:
c = np.vstack([a,b])

In [47]:
print(c)

[[10. 12.]
 [14. 16.]
 [18. 20.]
 [30. 32.]
 [34. 36.]
 [38. 40.]]


In [48]:
d = np.hstack([a,b])

In [49]:
print(d)

[[10. 12. 30. 32.]
 [14. 16. 34. 36.]
 [18. 20. 38. 40.]]


In [50]:
def maxxy(x,y):
    if x >= y:
        return x
    else:
        return y

In [51]:
maxxy(3,2)

3

In [55]:
a = np.array([1,2,3,2,3,4,3,5,8,6])
b = np.array([7,2,3,10,4,4,9,5,6,6])

In [56]:
maxxy(a,b)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
maxxyv = np.vectorize(maxxy)

In [58]:
maxxyv(a,b)

array([ 7,  2,  3, 10,  4,  4,  9,  5,  8,  6])

In [59]:
A = np.arange(1,10).reshape(3,3)

In [60]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
B = A[:,[2,1,0]]

In [64]:
print(B)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [66]:
C = A[[2,1,0],:]

In [67]:
print(C)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [68]:
A = np.matrix('1,2;3,4')

In [69]:
A

matrix([[1, 2],
        [3, 4]])

In [70]:
B = np.asmatrix(B)

In [71]:
B

matrix([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]])