In [1]:
import math as m

In [2]:
m.sin(30)

-0.9880316240928618

In [3]:
L = [0, 30, 45, 60, 90]

In [5]:
list(map(m.sin,L))

[0.0,
 -0.9880316240928618,
 0.8509035245341184,
 -0.3048106211022167,
 0.8939966636005579]

In [6]:
L

[0, 30, 45, 60, 90]

In [8]:
import numpy as np

In [9]:
A = np.array(L)

In [10]:
type(A)

numpy.ndarray

In [11]:
A

array([ 0, 30, 45, 60, 90])

In [13]:
L = [0.0, 30, 45, 60, 90]

In [14]:
L

[0.0, 30, 45, 60, 90]

In [24]:
A = np.array(L)

In [25]:
A

array([ 0., 30., 45., 60., 90.])

In [26]:
A.ndim

1

In [27]:
A.shape

(5,)

In [28]:
A.size

5

In [29]:
A.dtype

dtype('float64')

In [30]:
M = [[1,2,3],[4,5,6]]
B = np.array(M)
print(B)

[[1 2 3]
 [4 5 6]]


In [31]:
B.ndim

2

In [32]:
B.shape

(2, 3)

In [33]:
B.size

6

In [34]:
B.dtype

dtype('int32')

In [35]:
N = [[[2,3,4],[4,5,6]],[[1,2,3],[6,8,9]]]

In [37]:
C = np.array(N)

In [38]:
C.ndim

3

In [39]:
C.shape

(2, 2, 3)

In [40]:
C.size

12

In [41]:
len(C)

2

In [42]:
A

array([ 0., 30., 45., 60., 90.])

In [43]:
np.sin(A)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [44]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
C

array([[[2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 8, 9]]])

In [46]:
C.reshape(6,2)

array([[2, 3],
       [4, 4],
       [5, 6],
       [1, 2],
       [3, 6],
       [8, 9]])

In [47]:
C

array([[[2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 8, 9]]])

In [50]:
C.reshape(2,6)

array([[2, 3, 4, 4, 5, 6],
       [1, 2, 3, 6, 8, 9]])

In [51]:
C.flatten()

array([2, 3, 4, 4, 5, 6, 1, 2, 3, 6, 8, 9])

In [52]:
A

array([ 0., 30., 45., 60., 90.])

In [53]:
B = A.reshape(5,1)

In [54]:
B

array([[ 0.],
       [30.],
       [45.],
       [60.],
       [90.]])

In [55]:
A

array([ 0., 30., 45., 60., 90.])

In [56]:
A.shape

(5,)

In [57]:
B.shape

(5, 1)

In [58]:
A+B

array([[  0.,  30.,  45.,  60.,  90.],
       [ 30.,  60.,  75.,  90., 120.],
       [ 45.,  75.,  90., 105., 135.],
       [ 60.,  90., 105., 120., 150.],
       [ 90., 120., 135., 150., 180.]])

In [59]:
A = np.array([[1,2],[2,3]])
B = np.array([[1,1],[1,1]])

In [60]:
A*B

array([[1, 2],
       [2, 3]])

In [61]:
A@B

array([[3, 3],
       [5, 5]])

In [62]:
A.dot(B)

array([[3, 3],
       [5, 5]])

In [63]:
B@A

array([[3, 5],
       [3, 5]])

In [76]:
np.full((4,5),10.0)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [75]:
np.ones((4,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [79]:
np.eye(6,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.pi

3.141592653589793

In [82]:
np.e

2.718281828459045

In [83]:
np.inf

inf

In [84]:
np.nan

nan

In [87]:
np.log2(10)

3.321928094887362

In [88]:
np.sin(B)

array([[0.84147098, 0.84147098],
       [0.84147098, 0.84147098]])

In [89]:
A

array([[1, 2],
       [2, 3]])

In [90]:
L

[0.0, 30, 45, 60, 90]

In [91]:
L = np.array(L)

In [92]:
np.sin(L)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [93]:
np.sin(np.radians(L))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [94]:
B

array([[1, 1],
       [1, 1]])

In [95]:
C

array([[[2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [6, 8, 9]]])

In [102]:
C[0:1,1,2:3]

array([[6]])

In [103]:
L = [[10*i+j for j in range(0,6)] for i in range(1,6)]

In [104]:
L

[[10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [105]:
L[1][2] = 66

In [106]:
L

[[10, 11, 12, 13, 14, 15],
 [20, 21, 66, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [108]:
A = np.array(L)

In [111]:
A[1,2] = 22

In [112]:
A

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [149]:
np.diag(A,k=1)

array([11, 22, 33, 44, 55])

In [134]:
A[(0,1,2,3,4),(0,1,2,3,4)]

array([10, 21, 32, 43, 54])

In [133]:
A[(0,1,2,3,4),(0,3,1,4,2)]

array([10, 23, 31, 44, 52])

In [132]:
A[::-1,::-1]

array([[55, 54, 53, 52, 51, 50],
       [45, 44, 43, 42, 41, 40],
       [35, 34, 33, 32, 31, 30],
       [25, 24, 23, 22, 21, 20],
       [15, 14, 13, 12, 11, 10]])

In [131]:
A[4::-2,5::-2]

array([[55, 53, 51],
       [35, 33, 31],
       [15, 13, 11]])

In [129]:
A[-1::-2,(0,4)] #A[5::-2,(0,4)]

array([[50, 54],
       [30, 34],
       [10, 14]])

In [121]:
A[1:5:3,:]

array([[20, 21, 22, 23, 24, 25],
       [50, 51, 52, 53, 54, 55]])

In [159]:
R = np.random.randn(4,5)

In [160]:
R

array([[ 1.34313006, -0.26520268,  0.64098175,  0.89328013,  0.03164073],
       [ 1.65926612, -1.2267578 ,  1.24915397,  0.21859952, -1.53929427],
       [ 0.45769006,  0.42829425, -0.0286207 ,  0.8520644 ,  1.07115819],
       [-0.46592426,  1.69277962,  0.26923383, -0.34927919, -2.48359701]])

In [168]:
np.where(R > 0, R, 0)

array([[1.34313006, 0.        , 0.64098175, 0.89328013, 0.03164073],
       [1.65926612, 0.        , 1.24915397, 0.21859952, 0.        ],
       [0.45769006, 0.42829425, 0.        , 0.8520644 , 1.07115819],
       [0.        , 1.69277962, 0.26923383, 0.        , 0.        ]])

In [169]:
A

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [181]:
A.prod(axis=0)

array([12000000, 14973651, 18450432, 22486893, 27143424, 32484375])

In [182]:
L = [1,2,3,4]

In [1]:
import numpy as np

In [7]:
A = np.random.randint(20,50,(4,5))

In [8]:
A

array([[25, 38, 24, 22, 23],
       [47, 39, 39, 48, 24],
       [26, 23, 49, 42, 29],
       [32, 23, 40, 42, 40]])

In [16]:
A[::-2,::-2]

array([[40, 40, 32],
       [24, 39, 47]])

In [17]:
A

array([[25, 38, 24, 22, 23],
       [47, 39, 39, 48, 24],
       [26, 23, 49, 42, 29],
       [32, 23, 40, 42, 40]])

In [20]:
np.flipud(np.fliplr(A))[::2,::2]

array([[40, 40, 32],
       [24, 39, 47]])

In [21]:
A[::-2,::-2]

array([[40, 40, 32],
       [24, 39, 47]])

In [22]:
A

array([[25, 38, 24, 22, 23],
       [47, 39, 39, 48, 24],
       [26, 23, 49, 42, 29],
       [32, 23, 40, 42, 40]])

In [23]:
A[::-2,::2]

array([[32, 40, 40],
       [47, 39, 24]])

In [24]:
A

array([[25, 38, 24, 22, 23],
       [47, 39, 39, 48, 24],
       [26, 23, 49, 42, 29],
       [32, 23, 40, 42, 40]])

In [25]:
A[::2,::-2]

array([[23, 24, 25],
       [29, 49, 26]])

In [26]:
np.fliplr(A)[::2,::2]

array([[23, 24, 25],
       [29, 49, 26]])

In [27]:
A = np.random.rand(3,3)

In [28]:
A

array([[0.26907261, 0.07718774, 0.09116134],
       [0.32097697, 0.73188535, 0.16059292],
       [0.77064536, 0.35430231, 0.57596049]])

In [32]:
np.linalg.svd(A)

(array([[-0.21563899,  0.17584835, -0.96050881],
        [-0.56927548, -0.82183464, -0.02265495],
        [-0.79336325,  0.54190883,  0.27732575]]),
 array([1.24865854, 0.48547985, 0.08635334]),
 array([[-0.68245124, -0.57211757, -0.45490855],
        [ 0.41432306, -0.81551448,  0.40406996],
        [-0.60216003,  0.08727895,  0.79359037]]))

In [33]:
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [34]:
A

array([[0.26907261, 0.07718774, 0.09116134],
       [0.32097697, 0.73188535, 0.16059292],
       [0.77064536, 0.35430231, 0.57596049]])

In [35]:
B = np.random.rand(3,1)

In [36]:
B

array([[0.95292238],
       [0.65300259],
       [0.95080329]])

In [37]:
A+B

array([[1.22199499, 1.03011011, 1.04408372],
       [0.97397957, 1.38488794, 0.81359551],
       [1.72144865, 1.3051056 , 1.52676379]])

In [38]:
A

array([[0.26907261, 0.07718774, 0.09116134],
       [0.32097697, 0.73188535, 0.16059292],
       [0.77064536, 0.35430231, 0.57596049]])

In [39]:
B = np.random.rand(3,3)

In [40]:
A+B

array([[1.05595516, 0.31972922, 0.37277267],
       [0.99169985, 0.76543419, 0.32222292],
       [1.76963054, 0.72189678, 0.93687901]])

In [41]:
A = np.random.rand(2,3)

In [42]:
A

array([[0.34018502, 0.61553545, 0.76982072],
       [0.70559134, 0.33928632, 0.82704296]])

In [43]:
B

array([[0.78688255, 0.24254148, 0.28161132],
       [0.67072287, 0.03354884, 0.16163   ],
       [0.99898518, 0.36759448, 0.36091851]])

In [46]:
A = np.random.rand(1,3)

In [47]:
A

array([[0.78820806, 0.69827541, 0.50875367]])

In [48]:
B

array([[0.78688255, 0.24254148, 0.28161132],
       [0.67072287, 0.03354884, 0.16163   ],
       [0.99898518, 0.36759448, 0.36091851]])

In [49]:
A+B

array([[1.57509061, 0.9408169 , 0.790365  ],
       [1.45893093, 0.73182425, 0.67038368],
       [1.78719324, 1.06586989, 0.86967219]])

In [58]:
A = np.random.rand(3)

In [59]:
A.shape

(3,)

In [60]:
A+B

array([[1.24140124, 0.30000091, 0.75874155],
       [1.12524156, 0.09100827, 0.63876023],
       [1.45350387, 0.42505391, 0.83804874]])

In [67]:
A = np.random.rand(5,1)
B = np.random.rand(1,6)
C = np.random.rand(6)
D = np.array(4)

In [62]:
A.shape

(5, 1)

In [64]:
B.shape

(1, 6)

In [65]:
C.shape

(6,)

In [68]:
D.shape

()

In [71]:
A+B+C+D

array([[5.77365557, 5.42429212, 6.17796314, 5.67251123, 5.25514436,
        6.57009626],
       [5.59399939, 5.24463595, 5.99830697, 5.49285505, 5.07548819,
        6.39044009],
       [5.76495248, 5.41558903, 6.16926005, 5.66380814, 5.24644127,
        6.56139318],
       [5.02679173, 4.67742828, 5.4310993 , 4.92564739, 4.50828052,
        5.82323242],
       [5.89540043, 5.54603698, 6.299708  , 5.79425609, 5.37688922,
        6.69184112]])