In [1]:
import numpy as np

In [4]:
a = np.arange(0,10,3)

In [5]:
a

array([0, 3, 6, 9])

In [8]:
b = np.linspace(-10,0,20)

In [9]:
b

array([-10.        ,  -9.47368421,  -8.94736842,  -8.42105263,
        -7.89473684,  -7.36842105,  -6.84210526,  -6.31578947,
        -5.78947368,  -5.26315789,  -4.73684211,  -4.21052632,
        -3.68421053,  -3.15789474,  -2.63157895,  -2.10526316,
        -1.57894737,  -1.05263158,  -0.52631579,   0.        ])

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a.ndim

2

In [13]:
a.shape

(3, 4)

In [14]:
b = a.reshape(4,3)

In [15]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
b.shape

(4, 3)

In [18]:
c = a.reshape(2,3,2)

In [19]:
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [21]:
c.shape

(2, 3, 2)

In [22]:
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
a.shape

(3, 4)

In [25]:
O = np.zeros(a.shape)

In [26]:
O

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
O1 = np.zeros_like(a)

In [28]:
O1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
np.random.random((2,3))

array([[0.13034498, 0.16264559, 0.99262582],
       [0.98135595, 0.70809128, 0.49863672]])

In [30]:
a = np.random.rand(5,4)

In [31]:
a

array([[0.54386133, 0.85582814, 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [32]:
a[0,0]

0.5438613252432335

In [33]:
a[0]

array([0.54386133, 0.85582814, 0.67094719, 0.43048889])

In [34]:
a[0,:]

array([0.54386133, 0.85582814, 0.67094719, 0.43048889])

In [35]:
a[2]

array([0.59248   , 0.25710986, 0.88133172, 0.51002567])

In [36]:
a[2,:]

array([0.59248   , 0.25710986, 0.88133172, 0.51002567])

In [37]:
a

array([[0.54386133, 0.85582814, 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [38]:
a[:,2]

array([0.67094719, 0.86876955, 0.88133172, 0.04518304, 0.48528229])

In [40]:
a[0,[0,2]]

array([0.54386133, 0.67094719])

In [41]:
a

array([[0.54386133, 0.85582814, 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [42]:
a[[0,2,4],1]

array([0.85582814, 0.25710986, 0.40085009])

In [43]:
a[0:5:2,1]

array([0.85582814, 0.25710986, 0.40085009])

In [44]:
a

array([[0.54386133, 0.85582814, 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [64]:
a[[0,0,2,2],[0,2,0,2]]

array([3.        , 0.67094719, 0.59248   , 0.88133172])

In [63]:
a[0:3:2,0:3:2]

array([[3.        , 0.67094719],
       [0.59248   , 0.88133172]])

In [50]:
a[0,0:2] = [1,2]

In [51]:
a

array([[1.        , 2.        , 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [52]:
b = a[0,0:2]

In [53]:
b

array([1., 2.])

In [55]:
b[0] = 3

In [57]:
a

array([[3.        , 2.        , 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])

In [58]:
c = a[0,0:2].copy()

In [59]:
c

array([3., 2.])

In [60]:
c[0] = 5

In [61]:
a

array([[3.        , 2.        , 0.67094719, 0.43048889],
       [0.64879865, 0.25531965, 0.86876955, 0.55525017],
       [0.59248   , 0.25710986, 0.88133172, 0.51002567],
       [0.17248014, 0.32646354, 0.04518304, 0.47870044],
       [0.34074456, 0.40085009, 0.48528229, 0.46882893]])