### Scipy.linalg Package
- `scipy.linalg` package contains the linear algebraic functions to perform the operations on the matrices, solve the system of equations
 - `scipy.linalg` functions are coplied with BLAS/LAPACK support, which results in a faster execution

### Solving Linear Equations
- The `scipy.linalg.solve` feature solves the linear (system of) equations for the unknowns
- As an example, consider solving the sytem
$$
\begin{align*}
x + 2y + 5z &= 9\\
2x - 5y + z &= 8\\
2x - 3y + 8z &= 2
\end{align*}
$$

In [1]:
import numpy as np
from scipy.linalg import solve

A = np.array([[1,2,5],[2,-5,1],[2,-3,8]])
b = np.array([9,8,2])

x = solve(A,b)
print(x)

[11.71111111  2.75555556 -1.64444444]


### Finding a Determinant, Eigenvalues and Eigenvectors
- We can use `scipy.linalg.det` function to find the determinant of the given matrix.

In [2]:
from scipy.linalg import det
import numpy as np

A = np.array([[1,2],[3,4]])
d = det(A)

print(d)

-2.0


- For determining the eigenvalues and eigenvectors of a matrix, we can use `scipy.linalg.eig`

In [3]:
from scipy.linalg import eig
import numpy as np

A = np.array([[1,2],[3,4]])
L,V = eig(A)

print('Eigenvalues are: ',L)
print('Eigenvectors are: ',V)

Eigenvalues are:  [-0.37228132+0.j  5.37228132+0.j]
Eigenvectors are:  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Singular Value Decompostion
- A singular value decompostion (SVD) is a factorization of a real or complex matrix. 
- It generalizes the eigendecomposition of a square normal matrix with an orthonormal eigenbasis to any $m\times n$ matrix.
- It can be tought of as an extension of the eigenvalue problem to matrices that are not square.
- For a matrix $A$ of size $m \times n$ the factorization is of the form $M = U\Sigma V^*$, where $U$ is an $m \times m$ (complex) matrix, $\Sigma$ is a $m \times n$ rectangular diagonal matrix with non-negative real numbers on the diagonal, $V$ is an $n \times n$ (complex) matrix and $V^*$ is the conjugate transpose of $V$.
- SVD of a matrix can be found by using `scipy.linalg.svd`. The output of this function is $U, s, Vh$ where $U$ and $Vh$ are two unitary matrices and $s$ is a $1-$D array of singluar values (real, non-negative) such that that $\Sigma = {\rm diagonal~matrix~of}~s$ and $A = U\Sigma Vh$.

### Python code sample to demonstrate SVD

In [1]:
from scipy import linalg
import numpy as np

# Creating a random matrix A with real entries
A = np.random.rand(3,2)

# SVD demcomposition of A
U, s, Vh = linalg.svd(A)

print("U = ",U)
print("s = ",s)
print("Sigma = ",np.diag(s))
print("Vh =",Vh)

U =  [[-0.56853334  0.74647834 -0.34574547]
 [-0.36304901 -0.60480326 -0.70880775]
 [-0.73821763 -0.27745829  0.61485904]]
s =  [1.27236314 0.43443192]
Sigma =  [[1.27236314 0.        ]
 [0.         0.43443192]]
Vh = [[-0.68794998 -0.7257581 ]
 [ 0.7257581  -0.68794998]]


In [5]:
from scipy import linalg
import numpy as np

# Creating a random matrix A with complex entries
A = np.random.rand(3,2) + 1.j*np.random.randn(3,2)

# SVD demcomposition of A
U, s, Vh = linalg.svd(A)

print("U = ",U)
print("s = ",s)
print("Sigma = ",np.diag(s))
print("Vh =",Vh)

U =  [[-0.41486497+0.42009113j  0.7441306 -0.15704137j -0.1991394 -0.18265174j]
 [-0.36601581+0.01622119j -0.51437885-0.1103086j  -0.52433991-0.56043142j]
 [-0.52071958+0.49601505j -0.38009242-0.01959137j  0.54780063+0.19462937j]]
s =  [2.43101371 0.39425364]
Sigma =  [[2.43101371 0.        ]
 [0.         0.39425364]]
Vh = [[-0.68931548+0.j         -0.02392102-0.72406627j]
 [ 0.7244613 +0.j         -0.02276054-0.68893961j]]
